name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies
        run: brew bundle --no-upgrade

      - name: Run canonical test suite
        run: make test
